name: ${project.name}
version: ${project.version}
description: The most complex currency plugin ever made for Minecraft!

author: ${plugin.author}
website: ${plugin.website}

main: ${plugin.main}
database: true

commands:
    currencies:
        description: The central command for Currencies.
        aliases: cur
        usage: | 
            ${currencies.create}
            ${currencies.delete}
            ${currencies.addprime}
            ${currencies.addparent}
            ${currencies.addchild}
            ${currencies.list}
            ${currencies.openaccount}
            ${currencies.setdefault}
            ${currencies.balance}
            ${currencies.pay}
            ${currencies.bill}
            ${currencies.paybill}
            ${currencies.transactions}
            ${currencies.credit}
            ${currencies.debit}
            ${currencies.bankrupt}
    openaccount:
        description: Opens a bank account usually for a non-player.
        usage: ${currencies.openaccount}
    setdefault:
        description: Set your default currency.
        usage: ${currencies.setdefault}
    balance:
        description: Check your balance.
        usage: ${currencies.balance}
    pay:
        description: Pay another account.
        usage: ${currencies.pay}
    bill:
        description: Bill another account.
        usage: ${currencies.bill}
    paybill:
        description: Pay a bill you received from another account.
        usage: ${currencies.paybill}
    transactions:
        description: See your transaction history.
        usage: ${currencies.transactions}
    credit:
        description: Admin command for giving a player money.
        usage: ${currencies.credit}
    debit:
        description: Admin command for removing a player's money.
        usage: ${currencies.debit}
    bankrupt:
        description: Admin command for setting/resetting a player's balance.
        usage: ${currencies.bankrupt}
